### ISSUE TITLE
Giúp Cường tạo tài khoản github và add vào repository này.

### ISSUE THREAD

**Issue by rinodung** [Tien712/moodle#2]
Em giúp cường tạo tài khoản trên github để mình làm việc nhóm cho dễ nha em.

**Comment by Tien712** [comment]
Dạ em sẽ hướng dẫn bạn Cường.
Cám ơn anh. :D

2015-07-22 15:34 GMT+07:00 Dong Dung notifications@github.com:

**Comment by Tien712** [comment]
Em chào anh Dũng,

Hiện giờ tụi em có một số thay đổi về hướng làm đồ án chuyên
ngành. Do Moodle cũng đã hoàn thành theo ý thầy Hải và cũng do
tụi em theo chuyên ngành về System và Bảo mật cho nên em và Cường
đang làm kế hoạch mới về xây dựng hạ tầng bảo mật cho hệ thống
trong doanh nghiệp.
Hiện tại, tụi em đã bàn giao quản trị Moodle cho phòng đào tạo
Trung tâm CITD.
Tụi em thông báo với anh về các việc đã hoàn thành:
- Hiện tại nhóm em đã hoàn thành việc cấu hình tường lửa CSF
  chống tấn công vào hệ thống.
- Chỉnh sửa lại giao diện Moodle theo như yêu cầu của thầy Hải và
  thầy cũng đã đồng ý.
  Vậy nên, tụi em muốn ngưng phát triển Moodle và sẽ bàn giao cho
  các bạn khác có cùng ý tưởng. Mong anh thông cảm vì sự thay đổi
  hướng đi của đồ án chuyên ngành của nhóm em.

Tụi em cảm ơn anh rất nhiều!

**Comment by rinodung** [comment]
OK em. Chúc các em thành công....
